init commit for stats server
Lefski/explore-with-me pull request #1
Opened 2023-10-17 00:29 UTC by Lefski

2023-10-18 18:47 UTC, z8q requested changes

2023-10-18 18:47 UTC, z8q commented on stats-service/pom.xml
> +    <url>http://maven.apache.org</url>
url можно будет убрать

2023-10-18 18:47 UTC, z8q commented on stats-service/pom.xml
> +            <version>3.8.1</version>
Про версии.
Те зависимости, которые уже включены в spring boot’овский BOM `spring-boot-dependencies`, от которого наследуется spring-boot-starter-parent, должны быть без версий.
А если используем что-то, чего там нет, тогда такая зависимость должна быть прописана в блоке <dependencyManagement> корневого pom’а, где и будет указана версия. А в pom’е самого модуля (где зависимость непосредственно используется) должно быть всё равно без версии. Этим обеспечивается центральное место для управления версиями зависимостей и соответственно порядок в проекте.

2023-10-18 18:47 UTC, z8q commented on stats-service/server/src/main/java/ru/yandex/practicum/ewm/controller/StatsController.java
> +    private StatsService statsService;
Можно поставить final

2023-10-18 18:47 UTC, z8q commented on stats-service/server/src/main/resources/schema.sql
> +    ip  varchar(255)                            not null,
Можно посмотреть максимальную возможную длину ip, ограничить этим значением

2023-10-18 18:47 UTC, z8q commented on docker-compose.yml
> -  ewm-service:
Сборка сейчас падает, похоже не хватает модуля ewm-сервиса.
Нужно создать пустой модуль, но с  докер-файлом, pom,  и с классом-мейн, который помечается `@SpringBootApplication`, как StatsServerApp

2023-10-19 01:43 UTC, Lefski commented on stats-service/pom.xml
> +            <version>3.8.1</version>
Версию поправил, есть проблема со сборкой на гите. Почему-то скрипт wait-for-it.sh не может достучаться до контейнера на порте 9090. При этом на компьютере когда собираю в docker-compose up все работает корректно, приложение запускается на 9090 и отвечает на запросы.

2023-10-19 01:43 UTC, Lefski commented on stats-service/server/src/main/java/ru/yandex/practicum/ewm/controller/StatsController.java
> +    private StatsService statsService;
Готово

2023-10-19 01:45 UTC, Lefski commented on stats-service/server/src/main/resources/schema.sql
> +    ip  varchar(255)                            not null,
Готово, поставил 128

2023-10-19 02:25 UTC, Lefski commented on docker-compose.yml
> -  ewm-service:
Готово!

2023-10-19 18:46 UTC, Lefski commented on stats-service/pom.xml
> +    <url>http://maven.apache.org</url>
Готово, убрал!

2023-10-19 19:16 UTC, z8q requested changes

2023-10-19 19:16 UTC, z8q commented on docker-compose.yml
> +    ports:
ports у баз можно убрать

2023-10-19 19:16 UTC, z8q commented on docker-compose.yml
> +    environment:
В environment stats-server и ewm-service надо указать пароли к базам:
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=

2023-10-19 19:49 UTC, Lefski commented on docker-compose.yml
> +    ports:
поменял базы в docker-compose, убрал порты, убрал лишние volumes и build, теперь сборка зеленая

2023-10-20 21:05 UTC, z8q approved these changes

2023-10-20 23:06 UTC, merged