main-service
Lefski/explore-with-me pull request #2
Opened 2023-10-20 23:13 UTC by Lefski

2023-10-22 04:20 UTC, z8q requested changes

2023-10-22 04:20 UTC, z8q commented on main-service/src/main/java/ru/practicum/ewm/model/Event.java
>  public class Event {
Нужно добавить логику связанную с событиями:
контроллер-сервис-репозиторий

2023-10-22 04:20 UTC, z8q commented on main-service/src/main/java/ru/practicum/ewm/controller/AdminController.java
>  import org.springframework.http.ResponseEntity;
Стоит привести сборку к рабочему состоянию, чтобы проходили все тесты

2023-10-23 19:10 UTC, z8q requested changes

2023-10-23 19:10 UTC, z8q commented on main-service/src/main/java/ru/practicum/ewm/controller/AdminController.java
> +    @PatchMapping("events/{eventId}")
Нужно посмотреть по спецификации, каких методов не хватает.
Например тут реализован Patch /admin/events/{eventId}
но в спецификации еще есть Get /admin/events.
Надо посмотреть по всем методам.
Большая часть тестов постмана проходит, но все еще остаются ошибки при сборке. С ошибками не будет возможности принять работу

2023-10-23 19:10 UTC, z8q commented on main-service/src/main/java/ru/practicum/ewm/controller/AdminController.java
> +    @PatchMapping("events/{eventId}")
Можно было бы разделить на пакеты private, public, admin. И в них сделать контроллеры отдельно по событиям, отдельно по категориям и т.д.

2023-10-25 15:50 UTC, Lefski commented on main-service/src/main/java/ru/practicum/ewm/controller/AdminController.java
> +    @PatchMapping("events/{eventId}")
Пакеты решил не перекидывать, освоился со спецификацией и оставил такую структуру. Сборка зеленая, все тесты проходят!

2023-10-25 20:31 UTC, z8q approved these changes

2023-10-25 22:10 UTC, merged